In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib widget

In [2]:
import numpy as np
import random
import sys

sys.path.append('../tools')

import os

import torch

import pandas as pd
from sklearn.model_selection import train_test_split
import pytorch_lightning as pl
import pytorch_lightning.loggers as pl_loggers
import pytorch_lightning.callbacks as pl_callbacks
import data_utility, annotation_utility
from models.rns_dataloader import *
from active_learning_utility import get_strategy
from active_learning_data import Data
from active_learning_net import Net
from copy import deepcopy
from models.SwaV import SwaV
from models.LSTMDownStream import SupervisedDownstream
import warnings
import pickle
warnings.filterwarnings("ignore")


In [3]:
random_seed = 42
random.seed(random_seed)
torch.manual_seed(random_seed)
np.random.seed(random_seed)

if torch.cuda.is_available():
    torch.cuda.manual_seed(random_seed)
    # True ensures the algorithm selected by CUFA is deterministic
    torch.backends.cudnn.deterministic = True
    # torch.set_deterministic(True)
    # False ensures CUDA select the same algorithm each time the application is run
    torch.backends.cudnn.benchmark = False

import pytorch_lightning

pytorch_lightning.utilities.seed.seed_everything(seed=random_seed, workers=True)

Global seed set to 42


42

In [4]:
data_dir = "../../../user_data/"
log_folder_root = '../../../user_data/logs/'
ckpt_folder_root = '../../../user_data/checkpoints/'

In [5]:
strategy_name = 'KCenterGreedyPCA'

In [6]:
nStart = 1
nEnd = 20
nQuery = 2

In [7]:
args_task = {'n_epoch': 60,
             'transform_train': True,
             'strategy_name': strategy_name,
             'transform': False,
             'loader_tr_args': {'batch_size': 8, 'num_workers': 4, 'collate_fn': collate_fn,
                                'drop_last': True, 'persistent_workers': True},
             'loader_te_args': {'batch_size': 4, 'num_workers': 4, 'collate_fn': collate_fn,
                                'drop_last': True, 'persistent_workers': True}
             }

In [8]:
# raw_annotations = pd.read_csv(data_dir + 'full_updated_anns_annotTbl_cleaned.csv')
# ids = list(np.unique(raw_annotations[raw_annotations['descriptions'].notnull()]['HUP_ID']))
# # ids = list(np.unique(raw_annotations['HUP_ID']))
#
# data_import = data_utility.read_files(path=data_dir+'rns_data', path_data=data_dir+'rns_raw_cache', patientIDs=ids,
#                                       verbose=True)  # Import data with annotation

In [9]:
# data_list = os.listdir(data_dir+'rns_test_cache')
# print(data_list)
data_list = ['HUP047.npy', 'HUP084.npy', 'HUP096.npy', 'HUP109.npy', 'HUP121.npy', 'HUP129.npy', 'HUP131.npy',
             'HUP137.npy', 'HUP147.npy', 'HUP156.npy', 'HUP159.npy', 'HUP182.npy', 'HUP197.npy', 'HUP199.npy',
             'RNS026.npy', 'RNS029.npy']
# data_list = os.listdir(data_dir+'rns_test_cache')[1:]

# data_list = ['HUP182.npy',   'HUP129.npy',   'HUP109.npy', 'HUP156.npy', 'HUP096.npy', 'RNS026.npy',  'HUP159.npy']
# data_list = ['RNS026.npy', 'HUP159.npy', 'HUP129.npy', 'HUP096.npy', 'HUP182.npy']
train_data, train_label, test_data, test_label, train_index, test_index = get_data_by_episode(data_list, split=0.8)
# data, label,_,_ = get_data(data_list, split=1)
# train_data, test_data, train_label, test_label = sklearn.model_selection.train_test_split(data, label, test_size=0.8, random_state=42)

print(train_data.shape)
print(train_label.shape)
print(test_data.shape)
print(test_label.shape)

16it [00:03,  4.04it/s]

(992,)
(992,)
(270,)
(270,)


In [10]:
X_train = np.concatenate(train_data)
y_train = np.concatenate(train_label)
X_test = np.concatenate(test_data)
y_test = np.concatenate(test_label)
index_train = np.concatenate(train_index)
index_test = np.concatenate(test_index)
seq_len_train = np.array([y.shape[0] for y in train_label])
seq_len_test = np.array([y.shape[0] for y in test_label])

In [11]:
n_pool = len(train_data)
n_test = len(test_data)

NUM_INIT_LB = int(nStart * n_pool / 100)
NUM_QUERY = int(nQuery * n_pool / 100) if nStart != 100 else 0
NUM_ROUND = int((int(nEnd * n_pool / 100) - NUM_INIT_LB) / NUM_QUERY) if nStart != 100 else 0
if NUM_QUERY != 0:
    if (int(nEnd * n_pool / 100) - NUM_INIT_LB) % NUM_QUERY != 0:
        NUM_ROUND += 1

print(NUM_INIT_LB)
print(NUM_QUERY)
print(NUM_ROUND)

9
19
10


In [12]:
dataset = Data(X_train, y_train, X_test, y_test, seq_len_train, seq_len_test, RNS_Active_by_episode_LSTM, args_task)

In [13]:
swav = SwaV().load_from_checkpoint(
    ckpt_folder_root + 'rns_swav_50_12/rns_swav-epoch=82-swav_loss=2.58204.ckpt')
model = SupervisedDownstream(swav.backbone)
# initialize model and save the model state
modelstate = deepcopy(model.state_dict())
device = "cuda" if torch.cuda.is_available() else "cpu"

net = Net(model, args_task, device, ckpt_folder_root='rns_active', log_folder_root='rns_active')

In [14]:
strategy = get_strategy(strategy_name, dataset, net, None, args_task, rns_data=True)

In [15]:
# initial round of training, round 0
dataset.initialize_labels(NUM_INIT_LB)

In [16]:
# ids,_ = dataset.get_labeled_data()
# 
# selected_inds = {}
# selected_inds[0] = ids
# 
# if not os.path.exists(log_folder_root + 'rns_active_selected/' + strategy_name):
#     os.makedirs(log_folder_root + 'rns_active_selected/' + strategy_name)
# 
# # Serialize and save to a file
# with open(log_folder_root + 'rns_active_selected/' + strategy_name + '/' + 'selected_indices.pkl', 'wb') as f:
#     pickle.dump(selected_inds, f)

In [17]:
# strategy.train()

In [16]:
ckpt_save_n_step = 20

checkpoint_callback = pl_callbacks.ModelCheckpoint(monitor='train_loss',
                                                    filename=
                                                    strategy.net.params['strategy_name'] + '_round_' + str(strategy.net.round)
                                                    + '-{step}-{train_loss:.5f}',
                                                    dirpath=strategy.net.ckpt_folder_root + 'active_checkpoints_'
                                                            + strategy.net.params['strategy_name'],
                                                    save_top_k=-1,
                                                    every_n_train_steps=ckpt_save_n_step,
                                                    save_on_train_epoch_end=False)

early_stop_callback = pl_callbacks.EarlyStopping(monitor="val_acc",
                                                    patience=10,
                                                    verbose=False,
                                                    mode="max")

csv_logger = pl_loggers.CSVLogger(strategy.net.log_folder_root + "active_logs_" + strategy.net.params['strategy_name'],
                                    name='logger_round_' + str(strategy.net.round))

trainer = pl.Trainer(logger=csv_logger,
                        max_epochs=strategy.net.params['n_epoch'],
                        callbacks=[checkpoint_callback, early_stop_callback],
                        accelerator='gpu',
                        devices=1,
                        log_every_n_steps=50,
                        precision=16,
                        check_val_every_n_epoch=None,
                        val_check_interval=ckpt_save_n_step,
                        enable_model_summary=False,
                        )

strategy.net.trainer = trainer

Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


In [33]:

for rd in range(1, NUM_ROUND + 1):
    print('round ' + str(rd))
    log_file_name = log_folder_root + 'rns_active/active_logs_' + strategy_name + '/logger_round_' + str(
        rd - 1) + '/version_0/metrics.csv'
    logs = pd.read_csv(log_file_name)
    max_ind = logs['val_acc'].argmax()
    max_row = logs.iloc[max_ind]
    ckpt_directory = ckpt_folder_root + 'rns_active/active_checkpoints_' + strategy_name
    ckpt_files = os.listdir(ckpt_directory)
    load_file_name = strategy_name + '_round_' + str(rd - 1) + '-step=' + str(int(max_row['step']+1))
    print(load_file_name)

    ind = next((i for i, s in enumerate(ckpt_files) if load_file_name in s), None)
    print(ind, ckpt_files[ind])
    strategy.net.net = strategy.net.net.load_from_checkpoint(ckpt_directory + '/' + ckpt_files[ind], backbone=swav.backbone)

    q_idxs = strategy.query(NUM_QUERY*90)

    with open(log_folder_root + 'rns_active_selected/' + strategy_name + '/' + 'selected_indices.pkl', 'rb') as f:
    # Load the content of the file into a Python object
        selected_inds = pickle.load(f)
    selected_inds[rd] = q_idxs
    with open(log_folder_root + 'rns_active_selected/' + strategy_name + '/' + 'selected_indices.pkl', 'wb') as f:
        pickle.dump(selected_inds, f)
# Now you can use the dictionary object as usual
    strategy.update(q_idxs)
    strategy.net.round = rd
    strategy.net.net.load_state_dict(modelstate)
    torch.cuda.empty_cache()
    strategy.train()
    torch.cuda.empty_cache()

round 1


FileNotFoundError: [Errno 2] No such file or directory: '../../../user_data/logs/rns_active/active_logs_KCenterGreedyPCA/logger_round_0/version_0/metrics.csv'

In [20]:
rd = 1
print('round ' + str(rd))
strategy_name = 'MeanSTD'
log_file_name = log_folder_root + 'rns_active/active_logs_' + strategy_name + '/logger_round_' + str(
    rd - 1) + '/version_0/metrics.csv'
logs = pd.read_csv(log_file_name)
max_ind = logs['val_acc'].argmax()
max_row = logs.iloc[max_ind]
ckpt_directory = ckpt_folder_root + 'rns_active/active_checkpoints_' + strategy_name
ckpt_files = os.listdir(ckpt_directory)
load_file_name = strategy_name + '_round_' + str(rd - 1) + '-step=' + str(int(max_row['step']+1))
print(load_file_name)

ind = next((i for i, s in enumerate(ckpt_files) if load_file_name in s), None)
print(ind, ckpt_files[ind])
strategy.net.net = strategy.net.net.load_from_checkpoint(ckpt_directory + '/' + ckpt_files[ind], backbone=swav.backbone)

q_idxs = strategy.query(NUM_QUERY*90)

# with open(log_folder_root + 'rns_active_selected/' + strategy_name + '/' + 'selected_indices.pkl', 'rb') as f:
# # Load the content of the file into a Python object
#     selected_inds = pickle.load(f)
# selected_inds[rd] = q_idxs
# with open(log_folder_root + 'rns_active_selected/' + strategy_name + '/' + 'selected_indices.pkl', 'wb') as f:
#     pickle.dump(selected_inds, f)
# Now you can use the dictionary object as usual
strategy.update(q_idxs)
strategy.net.round = rd
strategy.net.net.load_state_dict(modelstate)
torch.cuda.empty_cache()
strategy.train()
torch.cuda.empty_cache()

round 1
MeanSTD_round_0-step=60
2 MeanSTD_round_0-step=60-train_loss=0.01130.ckpt


LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting: 0it [00:00, ?it/s]

100%|███████████████████████████████████████████████████████████| 1710/1710 [13:19<00:00,  2.14it/s]


[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True 

AssertionError: 

In [33]:
n = 50
from sklearn.decomposition import PCA
labeled_idxs, train_data = strategy.dataset.get_train_data_unaugmented()
embeddings, embeddings_t, seq_len = strategy.get_embeddings(train_data)
embeddings = embeddings_t.numpy()

labeled_idxs_copy = deepcopy(labeled_idxs)

# # downsampling embeddings if feature dim > 50
# if len(embeddings[0]) > 50:
#     pca = PCA(n_components=50)
#     embeddings = pca.fit_transform(embeddings)
# embeddings = embeddings.astype(np.float16)
# 
# norm_data = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)
# dist_mat = np.dot(norm_data, norm_data.T)
# mat = dist_mat[~labeled_idxs, :][:, labeled_idxs]
# 
# for i in tqdm(range(n), ncols=100):
#     mat_min = mat.min(axis=1)
#     q_idx_ = mat_min.argmax()
#     q_idx = np.arange(strategy.dataset.n_pool)[~labeled_idxs][q_idx_]
#     labeled_idxs[q_idx] = True
#     mat = np.delete(mat, q_idx_, 0)
#     mat = np.append(mat, dist_mat[~labeled_idxs, q_idx][:, None], axis=1)
# output = np.arange(strategy.dataset.n_pool)[(strategy.dataset.labeled_idxs ^ labeled_idxs)]
# norm_data = embeddings_t / np.linalg.norm(embeddings_t, axis=1, keepdims=True)
# norm_data_core = embeddings_t[output] / np.linalg.norm(embeddings_t[output], axis=1, keepdims=True)
# similarity_matrix = np.dot(norm_data, norm_data_core.T)
# dis = np.min(similarity_matrix, 1)
# dis[output] = 1
# uncertainties = dis
# to_select = strategy.metrics_distribution_rescaling(uncertainties, seq_len, labeled_idxs, n, descending=True)
# unlabeled_idxs, _ = strategy.dataset.get_unlabeled_data()
# print('selected', np.sum(to_select))
# assert len(to_select) == len(unlabeled_idxs)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting: 0it [00:00, ?it/s]

In [34]:
norm_data = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)
dist_mat = np.dot(norm_data, norm_data.T)
mat = dist_mat[~labeled_idxs, :][:, labeled_idxs]



In [35]:
n = 100
for i in tqdm(range(n), ncols=100):
    mat_min = mat.min(axis=1)
    q_idx_ = mat_min.argmax()
    q_idx = np.arange(strategy.dataset.n_pool)[~labeled_idxs][q_idx_]
    labeled_idxs[q_idx] = True
    mat = np.delete(mat, q_idx_, 0)
    mat = np.append(mat, dist_mat[~labeled_idxs, q_idx][:, None], axis=1)

output = np.arange(strategy.dataset.n_pool)[(strategy.dataset.labeled_idxs ^ labeled_idxs)]

norm_data = embeddings_t / np.linalg.norm(embeddings_t, axis=1, keepdims=True)
norm_data_core = embeddings_t[output] / np.linalg.norm(embeddings_t[output], axis=1, keepdims=True)
similarity_matrix = np.dot(norm_data, norm_data_core.T)
dis = np.min(similarity_matrix, 1)
dis[output] = 1
uncertainties = dis
to_select = strategy.metrics_distribution_rescaling(uncertainties, seq_len, labeled_idxs_copy, n, descending=True)
unlabeled_idxs, _ = strategy.dataset.get_unlabeled_data()
print('selected', np.sum(to_select))
assert len(to_select) == len(unlabeled_idxs)


100%|█████████████████████████████████████████████████████████████| 100/100 [00:16<00:00,  5.90it/s]


[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True 

In [30]:
labeled_idxs

array([False, False, False, ..., False, False, False])

In [24]:
uncertainties

array([0.6737734 , 0.7429988 , 0.7924017 , ..., 0.63798904, 0.6672902 ,
       0.6094841 ], dtype=float32)

In [23]:
dis

array([0.6737734 , 0.7429988 , 0.7924017 , ..., 0.63798904, 0.6672902 ,
       0.6094841 ], dtype=float32)

In [31]:
unlabeled_idxs

array([    0,     1,     2, ..., 85108, 85109, 85110])

In [21]:
labeled_idxs

array([False, False, False, ..., False, False, False])

In [29]:
len(to_select)

84082